### ISSUE TITLE
Volume slider sensitivity should impact scroll wheel 

### ISSUE THREAD

**Issue by isolasad** [Sv443/BetterYTM#43]
### Description of the feature:

Scroll wheel should change volume only by the same amount as "Volume slider sensitivity". I think that when the sensitivity is set to a number below 10, it should also affect the scroll wheel.  
Currently how I believe it works is that the scroll wheel always changes volume by a minimum of 10. So if I set the volume slider sensitivity to 15, the scroll wheel will increment volume by 15. However if I set the volume slider sensitivity to 5, the scroll wheel will still increment volume by 10. I think that when the sensitivity is set to a number below 10, it should also affect the scroll wheel. My apologies if this is formatted incorrectly; I am not a computer person.

**Comment by Sv443** [comment]
Thanks for submitting an issue!
I hadn't even considered scrolling on the volume slider as I always click and drag it.
I already finished this feature and it's in the development version now so it will be included in the next update.
If you want to be notified once it's released, make sure the "Notifications" on the right side of this page are enabled and your email notifications are enabled in your account settings. Once this issue is closed, that means the feature is available in the regular version of the userscript.
