### ISSUE TITLE
Fail to load when cookies are blocked

### ISSUE THREAD

**Issue by Katzenwerfer** [Sv443/BetterYTM#48]
### Checklist:

- [x] I checked [here](https://github.com/Sv443/BetterYTM/issues?q=is%3Aissue+sort%3Aupdated-desc) if there is already an issue for this bug
- [x] I am using the latest version of BetterYTM
- [x] I am using the latest version of my browser
- [x] I was able to reproduce the bug while all my other userscripts or extensions were disabled

### Description of the bug and steps to reproduce:

The current version of the script doesn't work whenever cookies are blocked on the site.
It does run according to the console, but it errors on some parts and ultimately doesn't load.
In the console, you can see the message `Uncaught DOMException: The operation is insecure.`.
This happens on Firefox (and derivatives), but I'm unsure if it's the same case for Chromium-based browsers.

### Environment:
- Browser name & version: LibreWolf 122.0.1-2
- Userscript version & build number: v1.1.0 (520689c)

### Other info / screenshots:

It runs.
![image](https://github.com/Sv443/BetterYTM/assets/53267697/f57fdf66-b1d6-41b1-b481-55c32bf7d87c)
Fails to load.
![image](https://github.com/Sv443/BetterYTM/assets/53267697/b6be54cf-3c86-4408-959c-ea3a634a7b46)

**Comment by Sv443** [comment]
Thanks for submitting the issue!
Honestly didn't even cross my mind to test with cookies disabled.
The thing that's throwing the error is the session storage not being available but it should be an easy-ish fix and I'm gonna try to get it done in [v1.1.1](https://github.com/Sv443/BetterYTM/pull/47)

**Comment by Sv443** [comment]
It's fixed now in the develop branch. You'll now see a warning instead and the sessionID is always set to `null`, so the script doesn't crash anymore.  
Since the sessionID isn't currently used anywhere, no feature is affected by the sessionID not existing, but with future updates that could change.  
  
![image](https://github.com/Sv443/BetterYTM/assets/38158426/b7f6cc5f-ce3f-41e9-813e-ad31063ecd2c)  
  
If you want, you can [install the latest development build.](https://github.com/Sv443/BetterYTM/raw/develop/dist/BetterYTM.user.js)  
It's technically an alpha but imo it's more than stable enough for regular use already.  
(The script should either auto-update itself once v1.1.1 is out or it will give you a prompt to manually install it, unless you disabled that in the config menu.)

**Comment by Sv443** [comment]
v1.1.1 is released now :)
