### ISSUE TITLE
Clear Queue Button

### ISSUE THREAD

**Issue by ozanmeral** [Sv443/BetterYTM#65]
### Description of the feature:
A button placed anywhere clears queue.

**Comment by Sv443** [comment]
Hi, thanks for the suggestion. I'm going to add a button that will remove the `&list` parameter from the URL, effectively clearing the queue or playlist while keeping the current song playing at its current time. As soon as this issue is closed, that means the update that contains this feature is released.

**Comment by ozanmeral** [comment]
Hi, thanks in advance. Appreciate your works.

**Comment by Sv443** [comment]
Thanks :)  
If you want to use it early you can install the development version [on this page](https://github.com/Sv443/BetterYTM/pull/52), just make sure to fully remove and reinstall it once the update is out.

**Comment by ozanmeral** [comment]
I've installed thanks. It's really better ytm :)

**Comment by Sv443** [comment]
New version is fully released now :)
